# Generated by Django 5.2.5 on 2025-09-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
