# Generated by Django 5.2.5 on 2025-09-16 15:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('track_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('favorite_color_answer', models.IntegerField(blank=True, null=True)),
                ('favorite_place_answer', models.IntegerField(blank=True, null=True)),
                ('current_mood_answer', models.IntegerField(blank=True, null=True)),
                ('favorite_hobby_answer', models.IntegerField(blank=True, null=True)),
                ('favorite_subject_answer', models.IntegerField(blank=True, null=True)),
                ('favorite_flower_answer', models.IntegerField(blank=True, null=True)),
                ('favorite_place', models.CharField(max_length=100)),
            ],
        ),
    ]
