# Generated by Django 5.2.5 on 2025-09-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_quiz_track_id_quiz_id_alter_quiz_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='favorite_place',
        ),
    ]
