# Generated by Django 5.2.5 on 2025-09-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_session_alter_quiz_session_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='SessionUser',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
