# Generated by Django 5.2.5 on 2025-09-17 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_session_sessionuser_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_color_answer', models.IntegerField(blank=True, null=True)),
                ('favorite_place_answer', models.IntegerField(blank=True, null=True)),
                ('current_mood_answer', models.IntegerField(blank=True, null=True)),
                ('favorite_hobby_answer', models.IntegerField(blank=True, null=True)),
                ('favorite_subject_answer', models.IntegerField(blank=True, null=True)),
                ('favorite_flower_answer', models.IntegerField(blank=True, null=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser')),
            ],
        ),
    ]
