# Generated by Django 5.2.5 on 2025-09-18 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_answermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='answer_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='answered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answermodel',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.quizmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='track_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
