# Generated by Django 5.2.5 on 2025-09-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_answermodel_answer_id_answermodel_answered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionuser',
            name='track_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
