# Generated by Django 5.2.5 on 2025-09-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_sessionuser_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmodel',
            old_name='session_id',
            new_name='session_user',
        ),
    ]
