# Generated by Django 5.2.5 on 2025-09-22 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_session_id_quizmodel_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='track_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
