# Generated by Django 5.2.5 on 2025-09-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_answermodel_track_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answermodel',
            name='answer_id',
        ),
    ]
