# Generated by Django 5.2.5 on 2025-09-22 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_answermodel_answer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.quizmodel'),
        ),
    ]
