# Generated by Django 5.2.5 on 2025-09-22 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_answermodel_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.quizmodel'),
        ),
    ]
