# Generated by Django 5.2.5 on 2025-09-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_answermodel_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.quizmodel'),
            preserve_default=False,
        ),
    ]
