# Generated by Django 5.2.6 on 2025-09-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
