# Generated by Django 5.2.6 on 2025-09-30 13:51

import dj_admin_plus.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=dj_admin_plus.fields.HTMLField(),
        ),
    ]
