# Generated by Django 5.2.6 on 2025-10-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_physics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physics',
            name='image',
        ),
    ]
