# Generated by Django 5.2.6 on 2025-10-10 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_physics10'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4)),
                ('physics_answer', models.IntegerField(blank=True, null=True)),
                ('physics2_answer', models.IntegerField(blank=True, null=True)),
                ('physics3_answer', models.IntegerField(blank=True, null=True)),
                ('physics4_answer', models.IntegerField(blank=True, null=True)),
                ('physics5_answer', models.IntegerField(blank=True, null=True)),
                ('physics6_answer', models.IntegerField(blank=True, null=True)),
                ('physics7_answer', models.IntegerField(blank=True, null=True)),
                ('physics8_answer', models.IntegerField(blank=True, null=True)),
                ('physics9_answer', models.IntegerField(blank=True, null=True)),
                ('physics10_answer', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
