# Generated by Django 5.2.6 on 2025-10-10 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_physicsanswermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicsanswermodel',
            name='session_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser'),
            preserve_default=False,
        ),
    ]
