# Generated by Django 5.2.6 on 2025-10-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_physicsanswermodel_session_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physics',
            name='name',
        ),
        migrations.AddField(
            model_name='physics',
            name='correct_answer',
            field=models.IntegerField(blank=True, choices=[(1, 'Option A'), (2, 'Option B'), (3, 'Option C'), (4, 'Option D')], null=True),
        ),
        migrations.AddField(
            model_name='physics',
            name='option_a',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='physics',
            name='option_b',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='physics',
            name='option_c',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='physics',
            name='option_d',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='physics',
            name='question',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
