# Generated by Django 5.2.6 on 2025-10-11 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_remove_physics_name_physics_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physics',
            name='question',
        ),
        migrations.AddField(
            model_name='physics',
            name='session_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physics',
            name='track_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
