# Generated by Django 5.2.6 on 2025-10-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_remove_physics_question_physics_session_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicsanswermodel',
            name='session_user',
        ),
    ]
