# Generated by Django 5.2.6 on 2025-10-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_remove_physicsanswermodel_session_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physics',
            name='session_user',
        ),
        migrations.AddField(
            model_name='physicsanswermodel',
            name='session_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser'),
            preserve_default=False,
        ),
    ]
