# Generated by Django 5.2.6 on 2025-10-11 08:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_physics_session_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physics2',
            name='name',
        ),
        migrations.AddField(
            model_name='physics2',
            name='correct_answer',
            field=models.IntegerField(blank=True, choices=[(1, 'Option A'), (2, 'Option B'), (3, 'Option C'), (4, 'Option D')], null=True),
        ),
        migrations.AddField(
            model_name='physics2',
            name='option_a',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='physics2',
            name='option_b',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='physics2',
            name='option_c',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='physics2',
            name='option_d',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='physics2',
            name='track_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
