# Generated by Django 5.2.6 on 2025-10-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_physicsquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Physics10',
        ),
        migrations.DeleteModel(
            name='Physics2',
        ),
        migrations.DeleteModel(
            name='Physics3',
        ),
        migrations.DeleteModel(
            name='Physics4',
        ),
        migrations.DeleteModel(
            name='Physics5',
        ),
        migrations.DeleteModel(
            name='Physics6',
        ),
        migrations.DeleteModel(
            name='Physics7',
        ),
        migrations.DeleteModel(
            name='Physics8',
        ),
        migrations.DeleteModel(
            name='Physics9',
        ),
        migrations.DeleteModel(
            name='PhysicsQuestion',
        ),
    ]
