# Generated by Django 5.2.6 on 2025-10-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_delete_physics10_delete_physics2_delete_physics3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicsanswermodel',
            name='physics10_answer',
        ),
        migrations.RemoveField(
            model_name='physicsanswermodel',
            name='physics2_answer',
        ),
        migrations.RemoveField(
            model_name='physicsanswermodel',
            name='physics3_answer',
        ),
        migrations.RemoveField(
            model_name='physicsanswermodel',
            name='physics4_answer',
        ),
        migrations.RemoveField(
            model_name='physicsanswermodel',
            name='physics5_answer',
        ),
        migrations.RemoveField(
            model_name='physicsanswermodel',
            name='physics6_answer',
        ),
        migrations.RemoveField(
            model_name='physicsanswermodel',
            name='physics7_answer',
        ),
        migrations.RemoveField(
            model_name='physicsanswermodel',
            name='physics8_answer',
        ),
        migrations.RemoveField(
            model_name='physicsanswermodel',
            name='physics9_answer',
        ),
    ]
