# Generated by Django 5.2.6 on 2025-10-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_physics_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physics',
            name='question_text',
        ),
    ]
