# Generated by Django 5.2.6 on 2025-10-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_remove_physics_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicsanswermodel',
            name='physics2_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicsanswermodel',
            name='physics3_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicsanswermodel',
            name='physics4_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicsanswermodel',
            name='physics5_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
