# Generated by Django 5.2.6 on 2025-10-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_physicsanswermodel_physics2_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physics',
            name='question_text',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
