# Generated by Django 5.2.6 on 2025-10-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_alter_physics_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='correct_answer',
            field=models.IntegerField(blank=True, choices=[(1, 'Option A'), (2, 'Option B'), (3, 'Option C'), (4, 'Option D'), (5, 'Option E')], null=True),
        ),
    ]
