# Generated by Django 5.2.6 on 2025-10-12 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_alter_chemistry_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemistryAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4)),
                ('chemistry_answer', models.IntegerField(blank=True, null=True)),
                ('chemistry2_answer', models.IntegerField(blank=True, null=True)),
                ('chemistry3_answer', models.IntegerField(blank=True, null=True)),
                ('chemistry4_answer', models.IntegerField(blank=True, null=True)),
                ('chemistry5_answer', models.IntegerField(blank=True, null=True)),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser')),
            ],
        ),
    ]
