# Generated by Django 5.2.6 on 2025-10-12 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_math'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4)),
                ('question_text', models.CharField(max_length=300)),
                ('option_a', models.CharField(blank=True, max_length=200, null=True)),
                ('option_b', models.CharField(blank=True, max_length=200, null=True)),
                ('option_c', models.CharField(blank=True, max_length=200, null=True)),
                ('option_d', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.IntegerField(blank=True, choices=[(1, 'Option A'), (2, 'Option B'), (3, 'Option C'), (4, 'Option D'), (5, 'Option E')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4)),
                ('question_text', models.CharField(max_length=300)),
                ('option_a', models.CharField(blank=True, max_length=200, null=True)),
                ('option_b', models.CharField(blank=True, max_length=200, null=True)),
                ('option_c', models.CharField(blank=True, max_length=200, null=True)),
                ('option_d', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.IntegerField(blank=True, choices=[(1, 'Option A'), (2, 'Option B'), (3, 'Option C'), (4, 'Option D'), (5, 'Option E')], null=True)),
            ],
        ),
    ]
