# Generated by Django 5.2.6 on 2025-10-12 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_capital_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4)),
                ('capital_answer', models.IntegerField(blank=True, null=True)),
                ('capital2_answer', models.IntegerField(blank=True, null=True)),
                ('capital3_answer', models.IntegerField(blank=True, null=True)),
                ('capital4_answer', models.IntegerField(blank=True, null=True)),
                ('capital5_answer', models.IntegerField(blank=True, null=True)),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser')),
            ],
        ),
        migrations.CreateModel(
            name='CarAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4)),
                ('car_answer', models.IntegerField(blank=True, null=True)),
                ('car2_answer', models.IntegerField(blank=True, null=True)),
                ('car3_answer', models.IntegerField(blank=True, null=True)),
                ('car4_answer', models.IntegerField(blank=True, null=True)),
                ('car5_answer', models.IntegerField(blank=True, null=True)),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser')),
            ],
        ),
        migrations.CreateModel(
            name='MathAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4)),
                ('math_answer', models.IntegerField(blank=True, null=True)),
                ('math2_answer', models.IntegerField(blank=True, null=True)),
                ('math3_answer', models.IntegerField(blank=True, null=True)),
                ('math4_answer', models.IntegerField(blank=True, null=True)),
                ('math5_answer', models.IntegerField(blank=True, null=True)),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser')),
            ],
        ),
        migrations.CreateModel(
            name='RiddleAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4)),
                ('riddle_answer', models.IntegerField(blank=True, null=True)),
                ('riddle2_answer', models.IntegerField(blank=True, null=True)),
                ('riddle3_answer', models.IntegerField(blank=True, null=True)),
                ('riddle4_answer', models.IntegerField(blank=True, null=True)),
                ('riddle5_answer', models.IntegerField(blank=True, null=True)),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser')),
            ],
        ),
    ]
