# Generated by Django 5.2.6 on 2025-10-31 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField(default=uuid.uuid4)),
                ('person_answer', models.IntegerField(blank=True, null=True)),
                ('person2_answer', models.IntegerField(blank=True, null=True)),
                ('person3_answer', models.IntegerField(blank=True, null=True)),
                ('person4_answer', models.IntegerField(blank=True, null=True)),
                ('person5_answer', models.IntegerField(blank=True, null=True)),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionuser')),
            ],
        ),
    ]
