# Generated by Django 5.2.6 on 2025-11-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_personanswermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
