# Generated by Django 5.2.6 on 2025-11-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_blog_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image2',
        ),
    ]
